# src/vlamguard/integrations/issues.py
"""Build issue body and create GitHub/GitLab issues from VlamGuard analysis."""

import subprocess

from vlamguard.integrations import IssueCreationError, run_cmd
from vlamguard.models.report import PlatformInfo
from vlamguard.models.response import AnalyzeResponse, PolicyCheckResult, Recommendation


def select_labels(checks: list[PolicyCheckResult]) -> list[str]:
    """Select issue labels based on failed check categories."""
    failed = [c for c in checks if not c.passed]
    has_security = any(
        c.category and ("security" == c.category or c.category.endswith("-security"))
        for c in failed
    )
    return ["security", "policy"] if has_security else ["bug"]


def build_issue_title(
    response: AnalyzeResponse,
    failed_checks: list[PolicyCheckResult],
) -> str:
    """Build issue title with prefix and summary stats."""
    labels = select_labels(failed_checks)
    prefix = "[Security]" if "security" in labels else "[Bug]"
    grade = f", grade {response.security_grade}" if response.security_grade else ""
    return (
        f"{prefix}: VlamGuard — {response.risk_level} risk, "
        f"{len(failed_checks)} failures{grade}"
    )


def build_issue_body(response: AnalyzeResponse) -> str:
    """Build markdown issue body from analysis response."""
    ai = response.ai_context
    meta = response.metadata
    grade_str = f" | **Grade:** {response.security_grade}" if response.security_grade else ""

    lines = [
        "## VlamGuard Analysis Report",
        "",
        f"**Risk Score:** {response.risk_score}/100 | **Risk Level:** {response.risk_level}{grade_str}",
        f"**Environment:** {meta.get('environment', 'unknown')} | **Manifests:** {meta.get('manifest_count', 0)}",
        "",
    ]

    # Summary
    if ai:
        lines.extend(["## Summary", "", ai.summary, ""])

    # Hard blocks
    if response.hard_blocks:
        lines.extend(["## Hard Blocks", ""])
        for hb in response.hard_blocks:
            lines.append(f"- `{hb}`")
        lines.append("")

    # Failed checks table
    failed = [c for c in response.policy_checks if not c.passed]
    if failed:
        lines.extend([
            "## Failed Policy Checks",
            "",
            "| Check ID | Name | Severity | Category | Message |",
            "|----------|------|----------|----------|---------|",
        ])
        for c in failed:
            lines.append(f"| {c.check_id} | {c.name} | {c.severity} | {c.category or '-'} | {c.message} |")
        lines.append("")

    # Recommendations
    if ai and ai.recommendations:
        lines.extend(["## Recommendations", ""])
        for rec in ai.recommendations:
            if isinstance(rec, str):
                lines.append(f"- {rec}")
            elif isinstance(rec, Recommendation):
                resource = f" ({rec.resource})" if rec.resource else ""
                reason = f": {rec.reason}" if rec.reason else ""
                lines.append(f"- **{rec.action}**{resource}{reason}")
                if rec.yaml_snippet:
                    lines.extend(["  ```yaml", f"  {rec.yaml_snippet}", "  ```"])
        lines.append("")

    # Security findings
    if response.security and response.security.secrets_detection:
        sd = response.security.secrets_detection
        if sd.confirmed_secrets > 0:
            lines.extend([
                "## Security Findings",
                "",
                f"**Secrets detected:** {sd.confirmed_secrets} confirmed, {sd.total_suspects} suspects",
                "",
            ])

    # Footer
    lines.extend([
        "---",
        "Generated by [VlamGuard](https://github.com/elky-bachtiar/VlamGuard)",
    ])

    return "\n".join(lines)


def create_issue(response: AnalyzeResponse, platform: PlatformInfo) -> str:
    """Create a GitHub/GitLab issue from analysis results.

    Args:
        response: VlamGuard analysis response (must have ai_context).
        platform: Detected platform info.

    Returns:
        URL of the created issue.

    Raises:
        IssueCreationError: If ai_context is missing or CLI fails.
    """
    if response.ai_context is None:
        raise IssueCreationError(
            "AI analysis required for issue creation. "
            "Remove --skip-ai or check AI configuration."
        )

    failed = [c for c in response.policy_checks if not c.passed]
    title = build_issue_title(response, failed)
    body = build_issue_body(response)
    labels = select_labels(failed)

    cmd = [platform.cli_command, "issue", "create", "--title", title]
    cmd.extend([platform.body_flag, body])
    for label in labels:
        cmd.extend(["--label", label])

    try:
        return run_cmd(cmd)
    except subprocess.CalledProcessError as e:
        raise IssueCreationError(
            f"Failed to create issue via {platform.cli_command}: "
            f"{e.stderr or e.stdout or str(e)}"
        ) from e
    except subprocess.TimeoutExpired:
        raise IssueCreationError(
            f"Timed out creating issue via {platform.cli_command}. "
            "Set VLAM_INTEGRATION_TIMEOUT for a longer timeout."
        )
