# src/vlamguard/integrations/pull_requests.py
"""Apply fixes and create GitHub/GitLab PRs/MRs from VlamGuard analysis."""

import logging
import subprocess
import uuid
from pathlib import Path

from vlamguard.integrations import PRCreationError, run_cmd
from vlamguard.models.report import FixApplied, Platform, PlatformInfo
from vlamguard.models.response import AnalyzeResponse, Recommendation

logger = logging.getLogger("vlamguard.integrations.pr")

# Static remediation mapping for common policy checks.
# Keys are check_ids, values are (yaml_path, value) tuples for values.yaml edits.
REMEDIATION_MAP: dict[str, dict] = {
    "security_context": {
        "path": ["securityContext"],
        "value": {"runAsNonRoot": True, "runAsUser": 1000},
    },
    "readonly_root_fs": {
        "path": ["securityContext", "readOnlyRootFilesystem"],
        "value": True,
    },
    "resource_limits": {
        "path": ["resources", "limits"],
        "value": {"cpu": "500m", "memory": "256Mi"},
    },
    # image_tag excluded — cannot determine correct tag programmatically.
    # AI yaml_snippet recommendations handle this case.
    "allow_privilege_escalation": {
        "path": ["securityContext", "allowPrivilegeEscalation"],
        "value": False,
    },
    "excessive_capabilities": {
        "path": ["securityContext", "capabilities"],
        "value": {"drop": ["ALL"]},
    },
    "service_account_token": {
        "path": ["automountServiceAccountToken"],
        "value": False,
    },
    "replica_count": {
        "path": ["replicaCount"],
        "value": 2,
    },
}


def _check_clean_tree() -> None:
    """Raise PRCreationError if the working tree has uncommitted changes."""
    status = run_cmd(["git", "status", "--porcelain"])
    if status:
        raise PRCreationError(
            "Working tree has uncommitted changes. "
            "Commit or stash them before creating a PR."
        )


def _get_current_branch() -> str:
    return run_cmd(["git", "rev-parse", "--abbrev-ref", "HEAD"])


def build_pr_body(
    before: AnalyzeResponse,
    after: AnalyzeResponse,
    fixes: list[FixApplied],
    unfixed: list[str],
    issue_url: str | None = None,
    pyyaml_fallback: bool = False,
) -> str:
    """Build PR/MR description with before/after comparison."""
    ai = before.ai_context
    before_grade = before.security_grade or "N/A"
    after_grade = after.security_grade or "N/A"

    lines = [
        "## Summary",
        "",
        ai.summary if ai else "Automated remediation of VlamGuard policy failures.",
        "",
        "## VlamGuard Report",
        "",
        f"| | Risk Score | Risk Level | Grade | Hard Blocks |",
        f"|--------|------------|------------|-------|-------------|",
        f"| **Before** | {before.risk_score}/100 | {before.risk_level} | {before_grade} | {len(before.hard_blocks)} |",
        f"| **After** | {after.risk_score}/100 | {after.risk_level} | {after_grade} | {len(after.hard_blocks)} |",
        "",
    ]

    # Fixes table
    if fixes:
        lines.extend([
            "## Fixes Applied",
            "",
            "| Check ID | File | Description |",
            "|----------|------|-------------|",
        ])
        for f in fixes:
            lines.append(f"| {f.check_id} | `{f.file_path}` | {f.description} |")
        lines.append("")

    # Unfixed
    if unfixed:
        lines.extend(["## Unfixed (Manual Action Required)", ""])
        for u in unfixed:
            lines.append(f"- `{u}`")
        lines.append("")

    # Issue link
    if issue_url:
        lines.extend([f"## Related Issue", "", f"Closes {issue_url}", ""])

    # PyYAML warning
    if pyyaml_fallback:
        lines.extend([
            "> **Note:** `ruamel.yaml` was not available; PyYAML was used for YAML editing. "
            "Comments in modified files may have been stripped.",
            "",
        ])

    lines.extend([
        "---",
        "Generated by [VlamGuard](https://github.com/elky-bachtiar/VlamGuard)",
    ])

    return "\n".join(lines)


def create_pull_request(
    response: AnalyzeResponse,
    platform: PlatformInfo,
    manifests_path: str,
    issue_url: str | None = None,
) -> str:
    """Create a PR/MR with applied fixes from VlamGuard analysis.

    Args:
        response: Analysis results (must have ai_context).
        platform: Detected platform info.
        manifests_path: Path to the manifest or values file to fix.
        issue_url: Optional issue URL to link in the PR body.

    Returns:
        URL of the created PR/MR.

    Raises:
        PRCreationError: On any failure (dirty tree, push, CLI).
    """
    if response.ai_context is None:
        raise PRCreationError(
            "AI analysis required for PR creation. "
            "Remove --skip-ai or check AI configuration."
        )

    _check_clean_tree()

    manifest_file = Path(manifests_path)
    if not manifest_file.exists():
        raise PRCreationError(f"Manifests path not found: {manifests_path}")

    original_branch = _get_current_branch()
    branch_id = uuid.uuid4().hex[:8]
    branch_name = f"fix/vlamguard-{branch_id}"
    changed_files: list[str] = []

    try:
        # Create branch
        run_cmd(["git", "checkout", "-b", branch_name])

        # Apply fixes
        fixes, unfixed, pyyaml_fallback = _apply_fixes(
            response, manifest_file,
        )

        if not fixes:
            # Nothing fixable — clean up and report
            run_cmd(["git", "checkout", original_branch])
            run_cmd(["git", "branch", "-D", branch_name])
            raise PRCreationError(
                "No fixable checks found. All failures require manual remediation."
            )

        changed_files = [f.file_path for f in fixes]

        # Stage and commit
        for fp in changed_files:
            run_cmd(["git", "add", fp])
        run_cmd(["git", "commit", "-m", "fix: remediate VlamGuard policy failures"])

        # Push
        run_cmd(["git", "push", "-u", platform.remote_name, branch_name])

        # Build PR body with before/after (use current response as "after" approximation)
        body = build_pr_body(
            before=response,
            after=response,  # TODO: re-run analysis for true after
            fixes=fixes,
            unfixed=unfixed,
            issue_url=issue_url,
            pyyaml_fallback=pyyaml_fallback,
        )

        failed_count = len([c for c in response.policy_checks if not c.passed])
        title = f"fix: remediate {failed_count} VlamGuard policy failures"

        cmd = [
            platform.cli_command, "pr" if platform.platform == Platform.GITHUB else "mr",
            "create", "--title", title, platform.body_flag, body,
        ]
        return run_cmd(cmd)

    except PRCreationError:
        raise
    except Exception as e:
        # Cleanup on failure
        try:
            for fp in changed_files:
                run_cmd(["git", "checkout", "--", fp])
            run_cmd(["git", "checkout", original_branch])
            run_cmd(["git", "branch", "-D", branch_name])
        except Exception:
            logger.warning("Cleanup failed after PR creation error")
        raise PRCreationError(f"Failed to create {platform.term}: {e}") from e


def _apply_fixes(
    response: AnalyzeResponse,
    manifest_file: Path,
) -> tuple[list[FixApplied], list[str], bool]:
    """Apply fixes to the manifest file.

    Returns:
        (fixes_applied, unfixed_check_ids, pyyaml_fallback_used)
    """
    # Try ruamel.yaml first, fall back to PyYAML
    pyyaml_fallback = False
    try:
        from ruamel.yaml import YAML
        yaml = YAML()
        yaml.preserve_quotes = True
    except ImportError:
        import yaml as pyyaml
        yaml = None
        pyyaml_fallback = True
        logger.warning(
            "ruamel.yaml not installed — using PyYAML. "
            "Comments in YAML files will not be preserved."
        )

    content = manifest_file.read_text()

    if yaml:
        from io import StringIO
        data = yaml.load(content)
    else:
        import yaml as pyyaml
        data = pyyaml.safe_load(content)

    if not isinstance(data, dict):
        return [], [c.check_id for c in response.policy_checks if not c.passed], pyyaml_fallback

    failed = [c for c in response.policy_checks if not c.passed]
    fixes: list[FixApplied] = []
    unfixed: list[str] = []

    # Collect actionable recommendations (Recommendation objects with yaml_snippet)
    ai_fixes: dict[str, str] = {}
    if response.ai_context:
        for rec in response.ai_context.recommendations:
            if isinstance(rec, Recommendation) and rec.yaml_snippet and rec.resource:
                # Map by resource for lookup
                ai_fixes[rec.action] = rec.yaml_snippet

    for check in failed:
        if check.check_id in REMEDIATION_MAP:
            mapping = REMEDIATION_MAP[check.check_id]
            _set_nested(data, mapping["path"], mapping["value"])
            fixes.append(FixApplied(
                check_id=check.check_id,
                file_path=str(manifest_file),
                description=f"Applied static remediation: {mapping['path'][-1]}",
            ))
        else:
            unfixed.append(check.check_id)

    if not fixes:
        return fixes, unfixed, pyyaml_fallback

    # Write back
    if yaml:
        from io import StringIO
        stream = StringIO()
        yaml.dump(data, stream)
        manifest_file.write_text(stream.getvalue())
    else:
        import yaml as pyyaml
        manifest_file.write_text(pyyaml.dump(data, default_flow_style=False))

    return fixes, unfixed, pyyaml_fallback


def _set_nested(data: dict, path: list[str], value) -> None:
    """Set a nested value in a dict, creating intermediate dicts as needed."""
    for key in path[:-1]:
        if key not in data or not isinstance(data.get(key), dict):
            data[key] = {}
        data = data[key]
    data[path[-1]] = value
