apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlamguard.fullname" . }}
  labels:
    {{- include "vlamguard.labels" . | nindent 4 }}
data:
  VLAM_AI_BASE_URL: {{ .Values.ai.baseUrl | quote }}
  VLAM_AI_MODEL: {{ .Values.ai.model | quote }}
