{{- if .Values.ai.apiKeySecret.sealedSecret.create }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "vlamguard.fullname" . }}-ai
  labels:
    {{- include "vlamguard.labels" . | nindent 4 }}
  {{- with .Values.ai.apiKeySecret.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    {{ .Values.ai.apiKeySecret.key | default "VLAM_AI_API_KEY" }}: {{ .Values.ai.apiKeySecret.sealedSecret.encryptedData | quote }}
  template:
    metadata:
      name: {{ include "vlamguard.fullname" . }}-ai
      labels:
        {{- include "vlamguard.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
