{{- if and .Values.ai.apiKeySecret.create (not .Values.ai.apiKeySecret.sealedSecret.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlamguard.fullname" . }}-ai
  labels:
    {{- include "vlamguard.labels" . | nindent 4 }}
type: Opaque
data:
  VLAM_AI_API_KEY: {{ .Values.ai.apiKeySecret.apiKey | b64enc | quote }}
{{- end }}
