"""JSON and Markdown report generation."""

from vlamguard.models.response import AnalyzeResponse


def generate_markdown(response: AnalyzeResponse) -> str:
    """Generate a Markdown risk report from an AnalyzeResponse."""
    lines: list[str] = []

    status = "BLOCKED" if response.blocked else "PASSED"
    lines.append(f"# VlamGuard Risk Report — {status}")
    lines.append("")
    lines.append(f"**Risk Score:** {response.risk_score}/100 ({response.risk_level.value.upper()})")
    lines.append(f"**Environment:** {response.metadata.get('environment', 'unknown')}")
    lines.append(
        f"**Decision:** {'BLOCKED — pipeline should fail' if response.blocked else 'PASSED — pipeline may proceed'}"
    )
    lines.append("")

    if response.hard_blocks:
        lines.append("## Hard Blocks")
        lines.append("")
        for block in response.hard_blocks:
            lines.append(f"- {block}")
        lines.append("")

    lines.append("## Policy Checks")
    lines.append("")
    lines.append("| Check | Result | Severity | Message |")
    lines.append("|-------|--------|----------|---------|")
    for check in response.policy_checks:
        icon = "PASS" if check.passed else "FAIL"
        lines.append(f"| {check.name} | {icon} | {check.severity} | {check.message} |")
    lines.append("")

    if response.ai_context:
        lines.append("## AI Analysis")
        lines.append("")
        lines.append(response.ai_context.summary)
        lines.append("")

        if response.ai_context.impact_analysis:
            lines.append("### Impact Analysis")
            lines.append("")
            for item in response.ai_context.impact_analysis:
                lines.append(
                    f"- **[{item.severity.upper()}]** {item.resource}: {item.description}"
                )
            lines.append("")

        if response.ai_context.recommendations:
            lines.append("### Recommendations")
            lines.append("")
            for i, rec in enumerate(response.ai_context.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        if response.ai_context.rollback_suggestion:
            lines.append("### Rollback")
            lines.append("")
            lines.append(f"```\n{response.ai_context.rollback_suggestion}\n```")
            lines.append("")
    else:
        lines.append("## AI Analysis")
        lines.append("")
        lines.append("AI context not available.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by VlamGuard*")
    return "\n".join(lines)
